title: Mariangel Reyes # your name (or website title) here
logo: "/images/me.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Hi there! I'm Mariangel Reyes, a data analyst and physicist. I'm passionate about teaching technical subjects, programming, academic research in astrophysics, and helping companies make data-driven decisions.<br><br>
  <a href="https://www.linkedin.com/in/angelsmreyes/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
